platform :ios, '7.0'

inhibit_all_warnings!
source 'https://github.com/CocoaPods/Specs.git'
link_with 'FoodCircles'

pod 'AFNetworking', '1.3.3'
pod 'FBSDKCoreKit', '~> 4.6'
pod 'FBSDKLoginKit', '~> 4.6'
pod 'Parse', '~> 1.8'
pod 'ParseFacebookUtilsV4'
pod 'ParseTwitterUtils', '~> 1.8'
pod 'FPPopover', '~> 1.4.1'
pod 'iCarousel', '~> 1.8.2'
pod 'MBProgressHUD', '~> 0.9'
pod 'RNBlurModalView', '~> 0.1.0'
pod 'SDWebImage', '~> 3.7.1'
pod 'SSKeychain', '~> 1.2.2'
pod 'TPKeyboardAvoiding', '~> 1.2.4'
pod 'PayPal-iOS-SDK'